@Host=http://127.0.0.1
@Port=3004
@EndpointTemplate=api/songs

## Get all songs
GET  {{Host}}:{{Port}}/{{EndpointTemplate}}/all

## Get song by ID
GET  {{Host}}:{{Port}}/{{EndpointTemplate}}/song/6924d615d75a06595b4de595

## Get songs by artist 


## DELETE song by ID
DELETE  {{Host}}:{{Port}}/{{EndpointTemplate}}/delete/6924ec79fa60f9f998552e6b

## Create a new song
POST  {{Host}}:{{Port}}/{{EndpointTemplate}}/create
Content-Type: application/json

{
    "title": " Baby ",
    "author": " Justin Bieber "
}

## Update a song by ID
PATCH  {{Host}}:{{Port}}/{{EndpointTemplate}}/update
Content-Type: application/json
{
    "id": " 6924e3b5dbfd2ab91103f468",
    "title": "Updated Song Title",
    "author": "Justin Bieber"
}